# Build Stage
FROM node:18 as build
WORKDIR /app

# Install dependencies and build the project
COPY package.json package-lock.json ./
RUN npm install

COPY . .
RUN npm run build

# Serve with NGINX
FROM nginx:alpine
COPY nginx.prod.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 5175
CMD ["nginx", "-g", "daemon off;"]
